export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const POST_MESSAGE_FAILURE = 'POST_MESSAGE_FAILURE'

export const UPDATE_NAME_INPUT = 'UPDATE_NAME_INPUT'
export const UPDATE_EMAIL_INPUT = 'UPDATE_EMAIL_INPUT'
export const UPDATE_MESSAGE_INPUT = 'UPDATE_MESSAGE_INPUT'